image: node:6.4
before_script:
  - npm install
test:
  script:
  - npm run test
pages:
  stage: deploy
  script:
  - npm run docs:build
  - cp -r docs/* public
  artifacts:
    paths:
    - public
  only:
  - master
