'use strict';

module.exports = {
  REQUEST_ADD_MESSAGE: 'REQUEST_ADD_MESSAGE',

  SHOW_TYPING_INDICATOR: 'SHOW_TYPING_INDICATOR',
  HIDE_TYPING_INDICATOR: 'HIDE_TYPING_INDICATOR',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  FEEDBACK_SET_ACTIVE: 'FEEDBACK_SET_ACTIVE',
  FEEDBACK_SET_DISABLE: 'FEEDBACK_SET_DISABLE',
  SET_FEEDBACK_MESSAGE_ID: 'SET_FEEDBACK_MESSAGE_ID',
  SET_FEEDBACK_RATING: 'SET_FEEDBACK_RATING'
};