'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  REQUEST_ADD_MESSAGE: 'REQUEST_ADD_MESSAGE',

  TOGGLE_SEARCH_VISIBILITY: 'TOGGLE_SEARCH_VISIBILITY',

  REQUEST_BOT: 'REQUEST_BOT',
  REQUEST_BOT_SUCCESS: 'REQUEST_BOT_SUCCESS',
  REQUEST_BOT_FAILURE: 'REQUEST_BOT_FAILURE',

  CHANGE_BOT_PER_PAGE: 'CHANGE_BOT_PER_PAGE',
  UPDATE_BOT_QUERY_TERM: 'UPDATE_BOT_QUERY_TERM',
  CLEAR_BOT_QUERY_TERM: 'CLEAR_BOT_QUERY_TERM',

  SHOW_TYPING_INDICATOR: 'SHOW_TYPING_INDICATOR',
  HIDE_TYPING_INDICATOR: 'HIDE_TYPING_INDICATOR',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  SET_FEEDBACK_MESSAGE_ID: 'SET_FEEDBACK_MESSAGE_ID',
  SET_FEEDBACK_RATING: 'SET_FEEDBACK_RATING',

  SET_BOT_STATUS: 'SET_BOT_STATUS',

  IGNORE_LOCATION: 'IGNORE_LOCATION' /* Called when user ignores Share location prompt */
};