module.exports = {
  REQUEST_ADD_MESSAGE: 'REQUEST_ADD_MESSAGE',
  REQUEST_ADD_MESSAGE_SUCCESS: 'REQUEST_ADD_MESSAGE_SUCCESS',

  SHOW_TYPING_INDICATOR: 'SHOW_TYPING_INDICATOR',
  HIDE_TYPING_INDICATOR: 'HIDE_TYPING_INDICATOR'
}
